#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_MAIN                                108
#define IDR_MENU                                129
#define IDD_SCREENSHOTSOPTIONS                  131
#define IDD_ASKFORFILENAME                      132
#define IDD_PNGOPTIONS                          133
#define IDD_ABOUT                               134
#define IDM_ALWAYSONTOP                         500
#define IDM_PASTEFROMCLIPBOARD                  501
#define IDM_SCREENSHOTSOPTIONS                  502
#define IDM_SHOWSCREENSHOTSDIRECTORY            503
#define IDM_CLEARLIST                           504
#define IDM_PNGOPTIONS                          505
#define IDM_ABOUT                               506
#define IDC_RADIO_DEFAULT                       1000
#define IDC_STATIC_VERSION                      1000
#define IDC_RADIO_CUSTOM                        1001
#define IDC_EDIT_DIRECTORY                      1002
#define IDC_BUTTON_BROWSE                       1003
#define IDC_CHECK_KEEPFILEDATE                  1003
#define IDC_CHECK_MAXIMIZECOMPRESSION           1008
#define IDC_CHECK_ASKFORFILENAME                1009
#define IDC_EDIT_FILENAME                       1010
#define IDC_CHECK_BACKUPOLDPNGFILES             1013
#define IDC_CHECK_KEEPINTERLACING               1014
#define IDC_CHECK_AVOIDGREYWITHSIMPLETRANSPARENCY 1016
#define IDC_CHECK_IGNOREANIMATEDGIFS            1017
#define IDC_STATIC_LOGO                         1018
#define IDC_STATIC_URL                          1019
#define IDC_GROUP_BKGD                          2000
#define IDC_RADIO_BKCOLOR_KEEP                  2020
#define IDC_RADIO_BKCOLOR_FORCE                 2021
#define IDC_RADIO_BKCOLOR_REMOVE                2022
#define IDC_STATIC_BKCOLDEC                     2024
#define IDC_STATIC_BKCOLHEX                     2025
#define IDC_STATIC_BKCOL                        2026
#define IDC_COLBUTTON_BKCOL                     2027
#define IDC_STATIC_COPYRIGHT                    2028
#define IDC_GROUP_TEXT                          3000
#define IDC_RADIO_TEXT_KEEP                     3001
#define IDC_RADIO_TEXT_FORCE                    3002
#define IDC_RADIO_TEXT_REMOVE                   3003
#define IDC_STATIC_KEYWORD                      3004
#define IDC_COMBO_TEXT_KEYWORD                  3005
#define IDC_EDIT_TEXT_DATA                      3006
#define IDC_GROUP_PHYS                          4000
#define IDC_RADIO_PHYS_REMOVE                   4001
#define IDC_RADIO_PHYS_KEEP                     4002
#define IDC_RADIO_PHYS_FORCE                    4003
#define IDC_EDIT_PPMX                           4004
#define IDC_STATIC_MULT1                        4005
#define IDC_EDIT_PPMY                           4006
#define IDC_EDIT_PPIX                           4007
#define IDC_STATIC_MULT2                        4008
#define IDC_EDIT_PPIY                           4009
